[project]
name = "regelrecht-mvp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.0"
dependencies = [
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "behave>=1.3.3",
    "pre-commit>=4.4.0",
    "ruff>=0.14.4",
]
